# 공통사항 정의
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost

logging:
  level:
    root: info
apiurl:
  member: http://api-gateway/member-service
  order: http://api-gateway/order-service
  item: http://api-gateway/item-service
