spring:
  profiles: gatewayserver
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/ember/(?<segment>.*), /$\{segment}
        - id: order
          uri: lb://ORDER
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/order/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: http://configserver:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
