spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_order
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  expiration: 30 #30분
  secretKey: my_token_secret
