
spring:
  kafka:
    kafka-server: localhost:9092
resilience4j:
  circuitbreaker:
    instances:
      productService:
        failureRateThreshold: 50  # 50% 이상의 실패율이면 OPEN 상태로 변경
        slowCallRateThreshold: 50  # 50% 이상의 요청이 느리면 OPEN 상태로 변경
        slowCallDurationThreshold: 2s  # 2초 이상 걸리면 "느린 호출"로 간주
        waitDurationInOpenState: 10s  # OPEN 상태에서 10초 동안 차단 후 HALF-OPEN 상태로 변경
        permittedNumberOfCallsInHalfOpenState: 2  # HALF-OPEN 상태에서 2개 요청이 모두 성공하면 → CLOSED 상태로 변경
        slidingWindowSize: 4  # 최근 4개의 요청을 기준으로 실패율 계산
        slidingWindowType: COUNT_BASED  # ✅ 요청 개수를 기준으로 실패율을 계산하도록 설정
        minimumNumberOfCalls: 1  # ✅ 최소 1개 요청이 이후부터 있어야 Circuit Breaker 활성화
        ignoreExceptions:
          - java.lang.IllegalArgumentException  # IllegalArgumentException 무시
