spring:
  kafka:
    kafka-server: localhost:9092
    consumer:
      #      groupid는 컨슈머 그룹을 식별하는 ID로서, 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume.
      #      만약 여러 컨슈머가 다른 gruop-id를 가지고 한 topic을 listen하면 각기 메시지를 수신하여 pub/sub과 같은 효과 발생
      group-id: product-group
      #     가장 처음 들어온 메시지부터 읽기시작(latest:현시점이후로 들어오는 메시지만 읽읃)
      auto-offset-reset: earliest
